const sampleCsv = [
    {
        Contract_No: '12-12',
        Vendor_No: '10001',
        v_vend_status: 'A',
        Vendor:	'SAMPLE VENDOR A',
        v_dba:	'VENDOR A SAMPLE CO.',
        address: '123 STREET NAME',
        v_vend_zip: '92008',	
        v_vend_city: 'CARLSBAD',	
        v_vend_state: 'CA',	
        v_vend_country: '',	
        v_email_addrs: 'SAMPLE@SAMPLE.COM',	
        v_contact1_name: 'CONTACT NAME',	
        v_contact1_phone: '8888888888',	
        v_email_cont1: 'CC_SAMPLE@SAMPLE.COM',	
        v_contact2_name: 'SECOND CONTACT NAME',
        v_contact2_phone: '8887776666',	
        v_email_cont2: 'CC_SECOND@SAMPLE.COM',	
        bqch_status_cd: '8',	
        Dept: '350',	
        Desc: 'SAMPLE INTEGRATION PROJECT A',	
        Est_Start: '1/6/2020',	
        Est_End: '6/30/2020',	
        Extended_through: '12/31/2024',	
        Days_Revised: '176',	
    },
    {
        Contract_No: '12-23',
        Vendor_No: '10001',
        v_vend_status: 'A',
        Vendor:	'SAMPLE VENDOR B',
        v_dba:	'VENDOR B SAMPLE CO.',
        address: '456 STREET NAME',
        v_vend_zip: '92007',	
        v_vend_city: 'CARLSBAD',	
        v_vend_state: 'CA',	
        v_vend_country: '',	
        v_email_addrs: 'TEST@TEST.COM',
        v_contact1_name: 'CONTACT NAME',	
        v_contact1_phone: '8888888888',	
        v_email_cont1: 'CC_TEST@TEST.COM',	
        v_contact2_name: 'SECOND CONTACT NAME',
        v_contact2_phone: '8887776666',	
        v_email_cont2: 'CC_SECOND@TEST.COM',	
        bqch_status_cd: '8',	
        Dept: '270',	
        Desc: 'SAMPLE INTEGRATION PROJECT A',	
        Est_Start: '1/6/2020',	
        Est_End: '6/30/2020',	
        Extended_through: '12/31/2024',	
        Days_Revised: '176',	
    }
];

export default sampleCsv;